/**
 * Chemical Elements Data Reference (Pauling Electronegativity, Radii, Masses, Polarizabilities, CPK Colors)
 */

import { ElementData } from '../types/chem';

export const ELEMENTS: Record<string, ElementData> = {
  H: {
    symbol: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    electronegativity: 2.20,
    covalentRadius: 31,
    vdwRadius: 120,
    atomicMass: 1.008,
    polarizability: 0.667,
    valenceElectrons: 1,
    standardValence: [1],
    color: '#E2E8F0',
  },
  He: {
    symbol: 'He',
    name: 'Helium',
    atomicNumber: 2,
    electronegativity: 0,
    covalentRadius: 28,
    vdwRadius: 140,
    atomicMass: 4.0026,
    polarizability: 0.205,
    valenceElectrons: 2,
    standardValence: [0],
    color: '#D9F99D',
  },
  Li: {
    symbol: 'Li',
    name: 'Lithium',
    atomicNumber: 3,
    electronegativity: 0.98,
    covalentRadius: 128,
    vdwRadius: 182,
    atomicMass: 6.94,
    polarizability: 24.3,
    valenceElectrons: 1,
    standardValence: [1],
    color: '#CC80FF',
  },
  Be: {
    symbol: 'Be',
    name: 'Beryllium',
    atomicNumber: 4,
    electronegativity: 1.57,
    covalentRadius: 96,
    vdwRadius: 153,
    atomicMass: 9.0122,
    polarizability: 5.60,
    valenceElectrons: 2,
    standardValence: [2],
    color: '#C2FF00',
  },
  B: {
    symbol: 'B',
    name: 'Boron',
    atomicNumber: 5,
    electronegativity: 2.04,
    covalentRadius: 84,
    vdwRadius: 192,
    atomicMass: 10.81,
    polarizability: 3.03,
    valenceElectrons: 3,
    standardValence: [3],
    color: '#FFB5B5',
  },
  C: {
    symbol: 'C',
    name: 'Carbon',
    atomicNumber: 6,
    electronegativity: 2.55,
    covalentRadius: 76,
    vdwRadius: 170,
    atomicMass: 12.011,
    polarizability: 1.76, // Reference carbon: 1.76 Angstrom^3
    valenceElectrons: 4,
    standardValence: [4],
    color: '#94A3B8',
  },
  N: {
    symbol: 'N',
    name: 'Nitrogen',
    atomicNumber: 7,
    electronegativity: 3.04,
    covalentRadius: 71,
    vdwRadius: 155,
    atomicMass: 14.007,
    polarizability: 1.10,
    valenceElectrons: 5,
    standardValence: [3, 5],
    color: '#38BDF8',
  },
  O: {
    symbol: 'O',
    name: 'Oxygen',
    atomicNumber: 8,
    electronegativity: 3.44,
    covalentRadius: 66,
    vdwRadius: 152,
    atomicMass: 15.999,
    polarizability: 0.802,
    valenceElectrons: 6,
    standardValence: [2],
    color: '#F43F5E',
  },
  F: {
    symbol: 'F',
    name: 'Fluorine',
    atomicNumber: 9,
    electronegativity: 3.98,
    covalentRadius: 57,
    vdwRadius: 147,
    atomicMass: 18.998,
    polarizability: 0.557,
    valenceElectrons: 7,
    standardValence: [1],
    color: '#2DD4BF',
  },
  Ne: {
    symbol: 'Ne',
    name: 'Neon',
    atomicNumber: 10,
    electronegativity: 0,
    covalentRadius: 58,
    vdwRadius: 154,
    atomicMass: 20.18,
    polarizability: 0.396,
    valenceElectrons: 8,
    standardValence: [0],
    color: '#B3E3F5',
  },
  Na: {
    symbol: 'Na',
    name: 'Sodium',
    atomicNumber: 11,
    electronegativity: 0.93,
    covalentRadius: 166,
    vdwRadius: 227,
    atomicMass: 22.99,
    polarizability: 24.1,
    valenceElectrons: 1,
    standardValence: [1],
    color: '#8B5CF6',
  },
  Mg: {
    symbol: 'Mg',
    name: 'Magnesium',
    atomicNumber: 12,
    electronegativity: 1.31,
    covalentRadius: 141,
    vdwRadius: 173,
    atomicMass: 24.305,
    polarizability: 10.6,
    valenceElectrons: 2,
    standardValence: [2],
    color: '#84CC16',
  },
  Al: {
    symbol: 'Al',
    name: 'Aluminum',
    atomicNumber: 13,
    electronegativity: 1.61,
    covalentRadius: 121,
    vdwRadius: 184,
    atomicMass: 26.982,
    polarizability: 6.80,
    valenceElectrons: 3,
    standardValence: [3],
    color: '#CBD5E1',
  },
  Si: {
    symbol: 'Si',
    name: 'Silicon',
    atomicNumber: 14,
    electronegativity: 1.90,
    covalentRadius: 111,
    vdwRadius: 210,
    atomicMass: 28.085,
    polarizability: 5.38,
    valenceElectrons: 4,
    standardValence: [4],
    color: '#F59E0B',
  },
  P: {
    symbol: 'P',
    name: 'Phosphorus',
    atomicNumber: 15,
    electronegativity: 2.19,
    covalentRadius: 107,
    vdwRadius: 180,
    atomicMass: 30.974,
    polarizability: 3.63,
    valenceElectrons: 5,
    standardValence: [3, 5],
    color: '#FB923C',
  },
  S: {
    symbol: 'S',
    name: 'Sulfur',
    atomicNumber: 16,
    electronegativity: 2.58,
    covalentRadius: 105,
    vdwRadius: 180,
    atomicMass: 32.06,
    polarizability: 2.90,
    valenceElectrons: 6,
    standardValence: [2, 4, 6],
    color: '#FACC15',
  },
  Cl: {
    symbol: 'Cl',
    name: 'Chlorine',
    atomicNumber: 17,
    electronegativity: 3.16,
    covalentRadius: 102,
    vdwRadius: 175,
    atomicMass: 35.45,
    polarizability: 2.18,
    valenceElectrons: 7,
    standardValence: [1],
    color: '#10B981',
  },
  K: {
    symbol: 'K',
    name: 'Potassium',
    atomicNumber: 19,
    electronegativity: 0.82,
    covalentRadius: 203,
    vdwRadius: 275,
    atomicMass: 39.098,
    polarizability: 43.4,
    valenceElectrons: 1,
    standardValence: [1],
    color: '#7C3AED',
  },
  Ca: {
    symbol: 'Ca',
    name: 'Calcium',
    atomicNumber: 20,
    electronegativity: 1.00,
    covalentRadius: 176,
    vdwRadius: 231,
    atomicMass: 40.078,
    polarizability: 22.8,
    valenceElectrons: 2,
    standardValence: [2],
    color: '#65A30D',
  },
  Fe: {
    symbol: 'Fe',
    name: 'Iron',
    atomicNumber: 26,
    electronegativity: 1.83,
    covalentRadius: 132,
    vdwRadius: 204,
    atomicMass: 55.845,
    polarizability: 8.4,
    valenceElectrons: 8,
    standardValence: [2, 3],
    color: '#E06633',
  },
  Cu: {
    symbol: 'Cu',
    name: 'Copper',
    atomicNumber: 29,
    electronegativity: 1.90,
    covalentRadius: 132,
    vdwRadius: 140,
    atomicMass: 63.546,
    polarizability: 6.7,
    valenceElectrons: 11,
    standardValence: [1, 2],
    color: '#C88033',
  },
  Zn: {
    symbol: 'Zn',
    name: 'Zinc',
    atomicNumber: 30,
    electronegativity: 1.65,
    covalentRadius: 122,
    vdwRadius: 139,
    atomicMass: 65.38,
    polarizability: 5.75,
    valenceElectrons: 12,
    standardValence: [2],
    color: '#7D80B0',
  },
  Br: {
    symbol: 'Br',
    name: 'Bromine',
    atomicNumber: 35,
    electronegativity: 2.96,
    covalentRadius: 120,
    vdwRadius: 185,
    atomicMass: 79.904,
    polarizability: 3.05,
    valenceElectrons: 7,
    standardValence: [1],
    color: '#991B1B',
  },
  I: {
    symbol: 'I',
    name: 'Iodine',
    atomicNumber: 53,
    electronegativity: 2.66,
    covalentRadius: 139,
    vdwRadius: 198,
    atomicMass: 126.904,
    polarizability: 5.35,
    valenceElectrons: 7,
    standardValence: [1],
    color: '#6B21A8',
  },
};

export const CARBON_REF = ELEMENTS['C'];

export function getElementData(symbol: string): ElementData {
  const norm = symbol.charAt(0).toUpperCase() + symbol.slice(1).toLowerCase();
  if (ELEMENTS[norm]) return ELEMENTS[norm];
  if (ELEMENTS[symbol.toUpperCase()]) return ELEMENTS[symbol.toUpperCase()];
  
  // Fallback generic element
  return {
    symbol: norm,
    name: norm,
    atomicNumber: 6,
    electronegativity: 2.5,
    covalentRadius: 77,
    vdwRadius: 170,
    atomicMass: 12.0,
    polarizability: 1.76,
    valenceElectrons: 4,
    standardValence: [4],
    color: '#94A3B8',
  };
}
